#!/bin/bash

VALGRIND=1
if [ "$1" = "-v" ]; then
	VALGRIND=0
fi

for eee in AAAA:0:1:somekey:6000 BBBB:0:1:somekey:6001; do
	sta=$(echo $eee | cut -f 1 -d ':')
	rep=$(echo $eee | cut -f 2 -d ':')
	cov=$(echo $eee | cut -f 3 -d ':')
	psk=$(echo $eee | cut -f 4 -d ':')
	port=$(echo $eee | cut -f 5 -d ':')
	if [ $VALGRIND = 1 ]; then
		valgrind --leak-check=full --error-exitcode=1 --log-file=${sta}.val --gen-suppressions=all \
			--suppressions=valgrind.supp ./testnet2 ${sta} ${rep} ${cov} ${psk} ${port} > ${sta}.log &
	else
		./testnet2 ${sta} ${rep} ${cov} ${psk} ${port} > ${sta}.log &
	fi
done
