#!/bin/bash

VALGRIND=1
if [ "$1" = "-v" ]; then
	VALGRIND=0
fi

make clean
make -j 4
if [ $VALGRIND = 1 ]; then
	valgrind --leak-check=full --suppressions=valgrind.supp --error-exitcode=1 ./test || exit 1
else
	./test || exit 1
fi

PIDS=""
for eee in AAAA:0:1 BBBB:1:1 CCCC:1:3 DDDD:0:2 EEEE:1:2; do
	sta=$(echo $eee | sed 's/:.*$//')
	rep=$(echo $eee | sed 's/^[^:]*://' | sed 's/:.*$//')
	cov=$(echo $eee | sed 's/^.*://')
	if [ $VALGRIND = 1 ]; then
		valgrind --leak-check=full --error-exitcode=1 --log-file=${sta}.val --gen-suppressions=all \
			--suppressions=valgrind.supp ./testnet ${sta} ${rep} ${cov} > ${sta}.log &
		PIDS+=" $!"
	else
		./testnet ${sta} ${rep} ${cov} > ${sta}.log &
		PIDS+=" $!"
	fi
done

ERR=0
for P in $PIDS; do
	if ! wait $P; then
		ERR=1
	fi
done
if [ "$ERR" != 0 ]; then
	echo
	echo Erro de execução, checar logs.
	echo
else
	make coverage
fi
