#!/bin/bash

VALGRIND=1
if [ "$1" = "-v" ]; then
	VALGRIND=0
fi

make clean
make -j 4
if [ $VALGRIND = 1 ]; then
	valgrind --leak-check=full --suppressions=valgrind.supp --error-exitcode=1 ./test || exit 1
else
	./test || exit 1
fi

PIDS=""
for eee in AAAA:0:1:somekey BBBB:1:1:somekey CCCC:1:3:somekey DDDD:0:2:somekey EEEE:1:2:None FFFF:0:3:None GGGG:1:2:badkey; do
	sta=$(echo $eee | cut -f 1 -d ':')
	rep=$(echo $eee | cut -f 2 -d ':')
	cov=$(echo $eee | cut -f 3 -d ':')
	psk=$(echo $eee | cut -f 4 -d ':')
	if [ $VALGRIND = 1 ]; then
		valgrind --leak-check=full --error-exitcode=1 --log-file=${sta}.val --gen-suppressions=all \
			--suppressions=valgrind.supp ./testnet ${sta} ${rep} ${cov} ${psk} > ${sta}.log &
		PIDS+=" $!"
	else
		./testnet ${sta} ${rep} ${cov} ${psk} > ${sta}.log &
		PIDS+=" $!"
	fi
done

ERR=0
for P in $PIDS; do
	if ! wait $P; then
		ERR=1
	fi
done
if [ "$ERR" != 0 ]; then
	echo
	echo Erro de execução, checar logs.
	echo
else
	make coverage
fi
