#!/bin/bash

make clean
make -j 4
valgrind --leak-check=full --suppressions=valgrind.supp --error-exitcode=1 ./test || exit 1
./test || exit 1
PIDS=""
valgrind --leak-check=full --error-exitcode=1 --log-file=AAAA.val --gen-suppressions=all --suppressions=valgrind.supp ./testnet AAAA > AAAA.log &
PIDS+=" $!"
valgrind --leak-check=full --error-exitcode=1 --log-file=BBBB.val --gen-suppressions=all --suppressions=valgrind.supp ./testnet BBBB > BBBB.log &
PIDS+=" $!"
valgrind --leak-check=full --error-exitcode=1 --log-file=CCCC.val --gen-suppressions=all --suppressions=valgrind.supp ./testnet CCCC > CCCC.log &
PIDS+=" $!"
valgrind --leak-check=full --error-exitcode=1 --log-file=CCCC.val --gen-suppressions=all --suppressions=valgrind.supp ./testnet DDDD > DDDD.log &
PIDS+=" $!"
ERR=0
for P in $PIDS; do
	if ! wait $P; then
		ERR=1
	fi
done
if [ "$ERR" != 0 ]; then
	echo
	echo Checar logs Valgrind!
	echo
else
	make coverage
fi
